# Generated by Django 2.2.7 on 2019-11-23 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0002_auto_20191123_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_at',
        ),
    ]
