# Generated by Django 2.2.7 on 2019-11-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0003_remove_book_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_at',
            field=models.BooleanField(default=True),
        ),
    ]
