# Generated by Django 2.2.7 on 2019-11-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0004_book_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(choices=[(0, 'Hobbit'), (1, 'Lord of the rings'), (2, 'Here and there')], default=(2, 'Here and there'), max_length=36, unique=True),
        ),
    ]
