# Generated by Django 2.2.7 on 2019-11-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0005_auto_20191123_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(choices=[('Hobbit', 0), ('Lord of the rings', 1), ('Here and there', 2)], default=('Here and there', 2), max_length=36, unique=True),
        ),
    ]
