# Generated by Django 2.2.7 on 2019-11-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0006_auto_20191123_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(choices=[('HB', 'Hobbit'), ('LOTR', 'Lord of the rings'), ('HAT', 'Here and there')], default=('HAT', 'Here and there'), max_length=36, unique=True),
        ),
    ]
