# Generated by Django 2.2.7 on 2019-11-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0007_auto_20191123_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_at',
            new_name='is_published',
        ),
    ]
