# Generated by Django 2.2.7 on 2019-11-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0008_auto_20191123_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
