# Generated by Django 2.2.7 on 2019-11-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0010_auto_20191123_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='app_demo.Book')),
            ],
        ),
    ]
